export const programmingSkills = [
  "devicon-html5-plain-wordmark",
  "devicon-css3-plain-wordmark",
  "devicon-javascript-plain",
  "devicon-python-plain-wordmark",
  "devicon-go-original-wordmark",
  "devicon-nodejs-plain",
  "devicon-typescript-plain",
  "devicon-nestjs-plain",
  "devicon-bootstrap-plain-wordmark",
  "devicon-materialui-plain",
  "devicon-react-original-wordmark",
  "devicon-vuejs-plain",
  "devicon-express-original-wordmark",
  "devicon-jest-plain",
  //   "devicon-vuetify-plain",
  "devicon-mysql-plain",
  "devicon-mongodb-plain",
  //   "devicon-rabbitmq-original",
];

export const toolSkills = [
  "devicon-docker-plain",
  "devicon-git-plain",
  "devicon-github-original",
  "devicon-npm-original-wordmark",
  "devicon-figma-plain",
  "devicon-vscode-plain",
  "devicon-pycharm-plain",
  "devicon-codepen-plain",
  "devicon-firebase-plain",
  "devicon-amazonwebservices-plain-wordmark",
  "devicon-azure-plain",
];
